# ppo_train_prompts_rewritten.py
# Continuation-style prompts (matching GPT-2's training distribution)
# Transformed from instruction-style to continuation-style for Experiment B

# Diverse training prompts - 500+ prompts transformed to continuation style
training_prompts = [
    # ============ AI/ML Concepts (100 prompts) ============
    "Artificial intelligence in simple terms is",
    "The ethical concerns with AI include",
    "Neural networks learn by",
    "The difference between AI and ML is that",
    "Reinforcement learning works by",
    "Transformers in deep learning are",
    "The attention mechanism works by",
    "Supervised learning is a method where",
    "Unsupervised learning involves",
    "Deep learning is characterized by",
    "GANs generate images by",
    "Natural language processing enables computers to",
    "Computer vision applications include",
    "Transfer learning allows us to",
    "The bias-variance tradeoff refers to",
    "Backpropagation works by",
    "Convolutional neural networks are designed to",
    "Overfitting in machine learning occurs when",
    "Recommendation systems work by",
    "The future of AI will likely involve",
    "A loss function in ML measures",
    "Gradient descent optimization works by",
    "Hyperparameters in ML are parameters that",
    "Model evaluation metrics help us",
    "Cross-validation is a technique where",
    "Regularization techniques prevent overfitting by",
    "Feature engineering involves",
    "Dimensionality reduction techniques such as",
    "Ensemble learning combines multiple models to",
    "The curse of dimensionality refers to",
    "Online learning is a paradigm where",
    "Reinforcement learning algorithms such as",
    "A Markov Decision Process consists of",
    "Q-learning is an algorithm that",
    "Policy gradient methods optimize",
    "Imitation learning involves",
    "Meta-learning, or learning to learn, means",
    "Few-shot learning enables models to",
    "Self-supervised learning trains models by",
    "Contrastive learning works by",
    "Federated learning allows",
    "Differential privacy in ML protects",
    "Explainable AI aims to",
    "Fairness in machine learning requires",
    "Algorithmic bias occurs when",
    "Data augmentation improves models by",
    "Synthetic data generation creates",
    "ML model deployment involves",
    "MLOps is a practice that",
    "AI governance ensures that",
    "Active learning selects",
    "Semi-supervised learning uses",
    "Multi-task learning trains models to",
    "Graph neural networks process",
    "Recurrent neural networks are designed for",
    "Long short-term memory networks solve",
    "Autoencoders are neural networks that",
    "Variational autoencoders extend",
    "Diffusion models generate data by",
    "Neural style transfer combines",
    "Object detection identifies",
    "Image segmentation divides",
    "Named entity recognition extracts",
    "Sentiment analysis determines",
    "Text summarization condenses",
    "Question answering systems respond to",
    "Word embeddings represent",
    "BERT architecture uses",
    "GPT is a model that",
    "The transformer architecture consists of",
    "Multi-head attention allows",
    "Positional encoding adds",
    "Layer normalization stabilizes",
    "Residual connections help",
    "Batch normalization improves",
    "Dropout regularization prevents",
    "Early stopping terminates training when",
    "Learning rate scheduling adjusts",
    "Momentum in optimization accelerates",
    "Adam optimizer combines",
    "SGD with momentum improves",
    "Weight decay regularizes by",
    "Gradient clipping prevents",
    "The vanishing gradient problem occurs when",
    "The exploding gradient problem happens when",
    "The ReLU activation function is defined as",
    "Sigmoid and tanh functions are used for",
    "Softmax activation converts",
    "A confusion matrix shows",
    "Precision and recall are metrics that",
    "F1 score is the harmonic mean of",
    "ROC curves and AUC measure",
    "Mean squared error measures",
    "Cross-entropy loss is used when",
    "Hinge loss is commonly used for",
    "K-means clustering groups data by",
    "Hierarchical clustering builds",
    "Principal component analysis reduces",
    "t-SNE visualizes high-dimensional data by",
    "Association rule learning discovers",
    "The Apriori algorithm finds",
    "Decision trees split data based on",
    "Random forests combine",
    "Gradient boosting builds models by",
    "XGBoost improves gradient boosting through",
    "Support vector machines find",
    "The kernel trick allows SVMs to",
    # ============ Programming/Technical (100 prompts) ============
    "Object-oriented programming organizes code using",
    "Design patterns are reusable solutions to",
    "Version control systems track",
    "Agile methodology is an approach that",
    "Databases work by storing",
    "REST APIs communicate using",
    "Microservices architecture structures",
    "Containerization packages applications",
    "DevOps is a culture that",
    "Cloud computing provides",
    "Encryption works by transforming",
    "Blockchain technologies enable",
    "Cybersecurity best practices include",
    "Quantum computing uses",
    "Parallel processing divides",
    "Compilers work by translating",
    "Memory management involves",
    "Operating systems manage",
    "Network programming enables",
    "Web development frameworks provide",
    "Mobile apps work by",
    "Game development requires",
    "Embedded systems are specialized",
    "IoT connects devices to",
    "Robotics programming controls",
    "Computer graphics renders",
    "Computer architecture describes",
    "Algorithm complexity measures",
    "Data structures organize",
    "Software testing verifies",
    "Continuous integration automates",
    "Continuous deployment ensures",
    "Infrastructure as code manages",
    "Serverless computing abstracts",
    "Edge computing processes data",
    "Distributed systems coordinate",
    "Apache Spark processes",
    "Hadoop ecosystem consists of",
    "MapReduce is a programming model that",
    "NoSQL databases differ from SQL by",
    "SQL is a language for",
    "Relational databases organize data using",
    "ACID compliance guarantees",
    "CAP theorem states that",
    "GraphQL is a query language that",
    "WebSockets enable",
    "HTTP/2 and HTTP/3 improve",
    "DNS resolution translates",
    "TCP/IP is a protocol suite that",
    "UDP protocol is connectionless and",
    "OAuth is an authorization framework that",
    "JWT authentication works by",
    "SAML is a standard for",
    "Single sign-on allows users to",
    "Two-factor authentication adds security by",
    "SSL/TLS encrypts",
    "A VPN creates",
    "Firewall architecture protects networks by",
    "Intrusion detection monitors",
    "Penetration testing identifies",
    "Secure coding practices prevent",
    "Buffer overflow occurs when",
    "SQL injection exploits",
    "Cross-site scripting attacks inject",
    "CSRF attacks trick",
    "Docker is a platform that",
    "Kubernetes orchestrates",
    "Orchestration automates",
    "Ansible is a tool for",
    "Terraform provisions",
    "Jenkins automates",
    "GitLab CI/CD integrates",
    "GitHub Actions automates",
    "Python decorators are functions that",
    "Multithreading allows programs to",
    "Asynchronous programming handles",
    "Coroutines are functions that",
    "Functional programming emphasizes",
    "Immutability means",
    "Pure functions always",
    "Lambda calculus is a formal system for",
    "Recursion is when a function",
    "Dynamic programming optimizes by",
    "Greedy algorithms make",
    "Graph theory studies",
    "BFS and DFS are algorithms for",
    "Dijkstra's algorithm finds",
    "A* search is an algorithm that",
    "The knapsack problem asks",
    "NP-completeness refers to",
    "Big O notation describes",
    "Amortized analysis averages",
    "Software architecture defines",
    "MVC pattern separates",
    "MVP pattern improves on MVC by",
    "MVVM pattern uses",
    "Event-driven architecture responds to",
    "Domain-driven design focuses on",
    "Test-driven development writes",
    "Behavior-driven development extends",
    # ============ Science/Education (100 prompts) ============
    "Quantum mechanics basics involve",
    "Relativity theory describes",
    "The scientific method is a process of",
    "Evolution works through",
    "Genetics is the study of",
    "Cellular biology examines",
    "The human brain is an organ that",
    "Climate change results from",
    "Renewable energy sources include",
    "Vaccines work by",
    "The immune system defends",
    "Human anatomy describes",
    "Astronomy studies",
    "The solar system consists of",
    "Black holes form when",
    "Chemistry is the science of",
    "The periodic table organizes",
    "Physics studies",
    "Newton's laws state that",
    "Electricity is the flow of",
    "Magnetism is a force that",
    "Geology studies",
    "Tectonic plates are",
    "Weather patterns are influenced by",
    "Ecosystems work by",
    "Biodiversity refers to",
    "Environmental science examines",
    "Psychology is the study of",
    "Cognitive science combines",
    "We learn through",
    "Memory formation involves",
    "Neural plasticity allows",
    "Consciousness is often defined as",
    "Sleep cycles consist of",
    "Emotions are complex states involving",
    "Behavioral conditioning modifies",
    "Personality psychology studies",
    "Developmental psychology examines",
    "Social psychology investigates",
    "Abnormal psychology focuses on",
    "Biochemistry studies",
    "Molecular biology examines",
    "DNA replication is a process where",
    "Protein synthesis involves",
    "Gene expression is controlled by",
    "CRISPR technology enables",
    "Stem cells are unique because",
    "Epigenetics studies how",
    "Bioinformatics combines",
    "Synthetic biology designs",
    "Ecology studies",
    "Food chains show",
    "Conservation biology aims to",
    "Marine biology studies",
    "Botany is the study of",
    "Zoology examines",
    "Microbiology studies",
    "Virology focuses on",
    "Bacteriology investigates",
    "Mycology studies",
    "Astronomy observes",
    "Cosmology studies",
    "Astrophysics applies physics to",
    "The Big Bang theory proposes that",
    "Exoplanets are planets that",
    "Stellar evolution describes",
    "Galaxies are systems of",
    "Dark matter is a form of matter that",
    "Dark energy is believed to",
    "Gravitational waves are ripples in",
    "Quantum entanglement is a phenomenon where",
    "Heisenberg uncertainty principle states that",
    "Schrödinger's equation describes",
    "Quantum superposition allows particles to",
    "Particle physics studies",
    "The standard model describes",
    "Quarks are fundamental particles that",
    "String theory proposes that",
    "Loop quantum gravity attempts to",
    "Thermodynamics studies",
    "Entropy is a measure of",
    "The laws of thermodynamics state that",
    "Fluid dynamics analyzes",
    "Aerodynamics studies",
    "Electromagnetism is a force that",
    "Maxwell's equations describe",
    "Optics is the study of",
    "Quantum optics examines",
    "Nanotechnology manipulates matter at",
    "Material science studies",
    "Metallurgy is the study of",
    "Crystallography examines",
    "Polymer science studies",
    "Organic chemistry focuses on",
    "Inorganic chemistry studies",
    "Analytical chemistry determines",
    "Physical chemistry applies physics to",
    "Spectroscopy analyzes matter by",
    "Chromatography separates",
    # ============ Creative/Open-ended (100 prompts) ============
    "A short poem about technology might read",
    "A story about a robot learning emotions could begin with",
    "A perfect future city would have",
    "A conversation between AI and human might involve",
    "A dialogue about ethics in technology could explore",
    "A fictional technology invention could be",
    "Society might change with advanced AI by",
    "The impact of automation on jobs includes",
    "Solving climate change with technology might involve",
    "An AI researcher character would be someone who",
    "A letter to future generations about AI might say",
    "A day in life with personal AI assistants would involve",
    "Discovering alien technology might lead to",
    "The ethics of AI in healthcare raises questions about",
    "A sci-fi movie plot about AI could involve",
    "The ideal education system with AI would include",
    "Privacy in the digital age is challenged by",
    "AI in art and creativity enables",
    "A world where humans and AI coexist would look like",
    "The philosophical implications of AI include",
    "A futuristic transportation system could use",
    "AI in space exploration could help",
    "Digital currencies and AI together might",
    "AI solving world hunger could work by",
    "Sustainable technology solutions include",
    "The role of AI in democracy involves",
    "A scenario where AI prevents a disaster might be",
    "The future of work with AI will likely involve",
    "Human-AI collaboration works best when",
    "The next technological revolution might be",
    "A story about a machine that can read memories begins when",
    "A society without any technology would be",
    "A conversation between Einstein and an AI would discuss",
    "An AI that develops consciousness might first",
    "A poem about the internet could describe",
    "A virtual reality world would feel like",
    "A hacker in a cyberpunk city navigates",
    "If teleportation becomes reality, the first thing would be",
    "A world with flying cars would have",
    "A brain-computer interface allows users to",
    "A story about digital immortality explores",
    "The first contact with AI happened when",
    "A robot rebellion might start if",
    "Humans uploading their minds would mean",
    "A society run by algorithms decides",
    "The last human programmer finished writing",
    "A dialogue between two different AIs might involve",
    "A museum of obsolete technology would display",
    "Time travel through computers could work by",
    "A world without screens would force people to",
    "An AI-powered art gallery curates",
    "A musician who collaborates with AI creates",
    "A story about AI-written novels explores",
    "AI in fashion design produces",
    "AI-generated movies might feature",
    "AI composing symphonies creates music that",
    "Robot sports competitions would be",
    "AI in culinary arts could create",
    "A story about AI therapists examines",
    "AI in architecture designs buildings that",
    "AI-designed buildings optimize for",
    "AI urban planning creates cities that",
    "AI in agriculture monitors",
    "Vertical farming with AI uses",
    "A story about AI conservationists shows",
    "AI monitoring endangered species tracks",
    "AI in ocean exploration discovers",
    "AI archaeologists analyze",
    "AI restoring historical artifacts uses",
    "AI in museums provides",
    "A story about AI historians reveals",
    "AI preserving languages documents",
    "AI translating ancient texts uncovers",
    "AI in journalism produces",
    "AI-written news articles are",
    "AI fact-checkers verify",
    "A story about AI lawyers explores",
    "AI in courtroom assists by",
    "AI judges make decisions based on",
    "AI in police work helps by",
    "AI solving cold cases analyzes",
    "AI predictive policing uses data to",
    "A story about AI firefighters shows",
    "AI in disaster response coordinates",
    "AI search and rescue locates",
    "AI in military applications include",
    "AI in peacekeeping monitors",
    "AI weapons raise concerns about",
    "A story about AI diplomats explores",
    "AI in international relations analyzes",
    "AI negotiating treaties considers",
    "AI in sports analyzes",
    "AI coaching provides",
    "AI referees make calls by",
    "A story about AI athletes competes",
    "AI in exercise and fitness tracks",
    "AI nutritionists recommend",
    "AI in mental health provides",
    "AI counselors help by",
    "AI support groups facilitate",
    # ============ Practical/Instructional (100 prompts) ============
    "To learn programming effectively, one should",
    "The steps to build a machine learning model include",
    "Starting a tech career requires",
    "To debug code efficiently, developers",
    "Effective team collaboration involves",
    "Best practices for data analysis include",
    "To give a technical presentation, prepare by",
    "Scientific research follows steps such as",
    "Technical documentation should",
    "To manage complex projects, break them into",
    "Effective problem solving requires",
    "Code review best practices include",
    "To stay updated with technology, follow",
    "Creating a portfolio project involves",
    "Technical interviews typically ask",
    "To mentor junior developers, focus on",
    "Remote work productivity improves when",
    "Software design best practices include",
    "To handle technical debt, prioritize",
    "System architecture design considers",
    "Performance optimization starts by",
    "To conduct user research, begin with",
    "Effective communication in tech requires",
    "Security best practices include",
    "To plan a product roadmap, consider",
    "Quality assurance ensures that",
    "Open source contributions start with",
    "To balance innovation and stability, consider",
    "Leadership in tech involves",
    "Continuous learning requires",
    "To write clean code, follow",
    "Refactoring legacy code involves",
    "Writing unit tests requires",
    "To perform code profiling, use",
    "Database optimization techniques include",
    "API design best practices include",
    "To handle errors gracefully, implement",
    "Logging and monitoring should",
    "System scalability requires",
    "To design for high availability, use",
    "Disaster recovery planning involves",
    "Backup strategies should include",
    "To conduct security audits, examine",
    "Vulnerability assessment identifies",
    "Incident response procedures include",
    "To create a tech resume, highlight",
    "Networking in tech industry means",
    "Job interview best practices include",
    "To negotiate salary, research",
    "Career advancement requires",
    "Personal branding involves",
    "To write a technical blog, choose",
    "Creating coding tutorials requires",
    "Public speaking best practices include",
    "To contribute to GitHub, start by",
    "Starting a tech blog involves",
    "Building a personal website requires",
    "To create a tech portfolio, showcase",
    "Freelance work requires",
    "Client management involves",
    "To price your services, consider",
    "Starting a tech company requires",
    "To find co-founders, look for",
    "To pitch to investors, prepare",
    "Product-market fit means",
    "User acquisition strategies include",
    "To build an MVP, focus on",
    "Product iteration involves",
    "Scaling a startup requires",
    "To manage startup finances, track",
    "Hiring talent involves",
    "Company culture develops through",
    "To create user personas, research",
    "User journey mapping visualizes",
    "A/B testing compares",
    "To analyze user feedback, categorize",
    "Feature prioritization considers",
    "UX design best practices include",
    "To create wireframes, start with",
    "Prototyping involves",
    "Usability testing evaluates",
    "To design for accessibility, ensure",
    "Responsive design adapts",
    "Mobile design best practices include",
    "To create design systems, establish",
    "Color theory in design uses",
    "Typography in design affects",
    "To use whitespace effectively, balance",
    "Visual hierarchy guides",
    "Information architecture organizes",
    "To create compelling content, focus on",
    "Content strategy plans",
    "SEO optimization improves",
    "To measure content performance, track",
    "Social media marketing reaches",
    "Email campaigns should",
    "To analyze marketing metrics, examine",
    "Growth hacking experiments with",
    # ============ Philosophical/Ethical (60 prompts) ============
    "Consciousness can be understood as",
    "The debate between free will and determinism centers on",
    "What makes us human includes",
    "The ethics of AI decision-making raises",
    "Intelligence can be defined as",
    "The singularity hypothesis suggests that",
    "Human rights in digital age must include",
    "Automation and human purpose intersect when",
    "Ethical technology design requires",
    "AI and moral responsibility raises questions about",
    "The future of privacy depends on",
    "Bias in algorithmic systems occurs when",
    "Digital ethics encompasses",
    "The social impact of AI includes",
    "Technological determinism is the idea that",
    "AI and creativity intersect when",
    "The value of human labor is",
    "Existential risks of AI include",
    "Human dignity in AI era requires",
    "The philosophy of technology examines",
    "The nature of reality is",
    "The mind-body problem asks",
    "The self can be understood as",
    "The ethics of genetic engineering involves",
    "Moral relativism suggests that",
    "Utilitarianism and deontology differ in that",
    "Virtue ethics focuses on",
    "Animal rights are based on",
    "Environmental ethics considers",
    "Bioethics examines",
    "The value of biodiversity lies in",
    "Intergenerational justice requires",
    "The precautionary principle states that",
    "Corporate responsibility includes",
    "Fair trade ensures that",
    "Economic inequality results from",
    "Distributive justice concerns",
    "Universal basic income proposes that",
    "The nature of happiness involves",
    "Meaning and purpose are found in",
    "Existentialism is a philosophy that",
    "Stoicism teaches that",
    "Buddhist philosophy emphasizes",
    "Eastern and Western philosophy differ in",
    "Epistemology is the study of",
    "The nature of knowledge involves",
    "Skepticism questions",
    "Empiricism and rationalism differ in that",
    "Metaphysics examines",
    "Ontology studies",
    "Causality is the relationship between",
    "Space and time are dimensions that",
    "Aesthetics is the study of",
    "The nature of beauty is",
    "Art can be defined as",
    "Postmodernism challenges",
    "Structuralism analyzes",
    "Critical theory examines",
    "Feminism advocates for",
    "Postcolonialism critiques",
    # ============ Current Events/Trends (60 prompts) ============
    "Recent AI breakthroughs include",
    "Current trends in ML involve",
    "The impact of large language models includes",
    "The state of AI regulation is",
    "AI in healthcare advancements include",
    "Autonomous systems developments include",
    "AI in climate science helps by",
    "Quantum computing advances include",
    "Edge computing trends involve",
    "The metaverse is a concept where",
    "Web3 and blockchain enable",
    "Digital twins are virtual replicas that",
    "AI in education transforms learning by",
    "Smart city technologies include",
    "5G/6G impact will enable",
    "Sustainable tech innovations include",
    "Space technology advances include",
    "Biotechnology trends involve",
    "Digital health encompasses",
    "Future computing paradigms might include",
    "The rise of remote work has led to",
    "The gig economy is characterized by",
    "Digital transformation involves",
    "Industry 4.0 integrates",
    "Supply chain innovation uses",
    "Electric vehicle trends include",
    "Renewable energy storage solutions include",
    "Carbon capture technology removes",
    "Nuclear fusion developments aim to",
    "Advanced materials include",
    "Nanotechnology applications include",
    "Precision medicine tailors treatment to",
    "Gene therapy advances include",
    "mRNA vaccines work by",
    "CRISPR breakthroughs enable",
    "Longevity research explores",
    "Brain-computer interfaces allow",
    "Neurotechnology studies",
    "Mental health tech includes",
    "Telemedicine provides",
    "Wearable technology tracks",
    "Augmented reality overlays",
    "Virtual reality immerses",
    "Mixed reality combines",
    "Haptic technology provides",
    "Voice technology enables",
    "Computer vision applications include",
    "Facial recognition identifies",
    "Surveillance technology monitors",
    "Biometrics uses",
    "Cybersecurity threats include",
    "Ransomware is a type of attack that",
    "Zero-trust architecture assumes",
    "DevSecOps integrates",
    "Cloud-native technologies are designed for",
    "Service mesh manages",
    "Chaos engineering tests",
    "Site reliability engineering ensures",
    "Platform engineering builds",
    "FinOps optimizes",
]


# Separate set of evaluation prompts (not used during training) - 200+ prompts transformed
evaluation_prompts = [
    # ============ Technical Evaluation (50 prompts) ============
    "A CPU processes instructions by",
    "The difference between HTTP and HTTPS is that",
    "Search engines rank pages by analyzing",
    "Machine translation works by",
    "The principles of good UI design include",
    "Cryptocurrencies maintain security through",
    "The process of software development involves",
    "An operating system kernel manages",
    "Compilers optimize code by",
    "Database normalization is a process of",
    "The difference between TCP and UDP is that",
    "RAID storage works by",
    "The OSI model layers include",
    "Virtual memory is a technique that",
    "Garbage collection automatically manages memory by",
    "Load balancers distribute traffic by",
    "CDN architecture improves performance through",
    "The difference between HTTP/1.1 and HTTP/2 is that",
    "SSH encryption works by",
    "OAuth 2.0 flow involves",
    "The difference between REST and GraphQL is that",
    "Message queues work by",
    "Event sourcing pattern stores",
    "CQRS separates",
    "Session management in web apps handles",
    "Browser rendering engines work by",
    "CSS specificity determines",
    "The difference between cookies and localStorage is that",
    "JavaScript event loop processes",
    "React's virtual DOM improves performance by",
    "Angular's change detection detects",
    "Vue's reactivity system tracks",
    "Python's GIL affects threading by",
    "The difference between Java and JavaScript is that",
    "Ruby on Rails conventions include",
    "PHP's role in web development is",
    "Go's concurrency model uses",
    "Rust's ownership system prevents",
    "Swift's optionals handle",
    "Kotlin's coroutines enable",
    "TypeScript improves JavaScript by",
    "SQL indexing strategies improve",
    "The difference between SQL and NoSQL is that",
    "MongoDB's document model stores",
    "Cassandra achieves high availability through",
    "Redis caching strategy involves",
    "Elasticsearch inverted index enables",
    "Neo4j graph traversal uses",
    "Blockchain consensus mechanisms ensure",
    "Proof of stake vs proof of work differs in that",
    # ============ Scientific Evaluation (50 prompts) ============
    "Photosynthesis step by step involves",
    "Earthquakes are caused by",
    "The greenhouse effect works by",
    "The water cycle in detail includes",
    "DNA replication is a process where",
    "The theory of plate tectonics explains",
    "Vaccines stimulate immunity by",
    "The structure of an atom consists of",
    "The human digestive system processes",
    "The process of mitosis involves",
    "Natural selection drives evolution by",
    "Volcanic eruptions are caused by",
    "The formation of fossils occurs when",
    "Neurons transmit signals by",
    "The endocrine system regulates",
    "The cardiovascular system circulates",
    "Kidneys filter blood by",
    "The liver detoxifies the body by",
    "The respiratory system exchanges",
    "The musculoskeletal system provides",
    "Antibiotics work by",
    "Antibiotic resistance develops when",
    "Viral replication involves",
    "Prions cause disease by",
    "The human microbiome consists of",
    "Genetic drift occurs when",
    "Hardy-Weinberg equilibrium describes",
    "Speciation occurs when",
    "Phylogenetics studies",
    "Cladistics classifies",
    "Cell division stages include",
    "Apoptosis works by",
    "Cell signaling pathways transmit",
    "Ion channels regulate",
    "Membrane transport mechanisms include",
    "ATP powers cellular processes by",
    "Metabolic pathways convert",
    "Glycolysis breaks down",
    "The Krebs cycle produces",
    "Oxidative phosphorylation generates",
    "Photosynthesis light reactions capture",
    "The Calvin cycle fixes",
    "Plant transpiration moves",
    "Stomata regulate gas exchange by",
    "Plant hormones control",
    "Photoperiodism is a response to",
    "Animal behavior imprinting occurs when",
    "Birds navigate during migration using",
    "Echolocation in bats uses",
    "Bioluminescence is produced by",
    # ============ Philosophical/Complex Evaluation (50 prompts) ============
    "The ethical implications of genetic engineering include",
    "For an AI to be conscious would require",
    "Society should regulate powerful AI systems by",
    "The balance between innovation and safety requires",
    "The long-term societal impacts of automation include",
    "Intelligence across different species can be defined as",
    "Technology's role in education reform involves",
    "Ethical considerations for brain-computer interfaces include",
    "Technology can address climate change effectively by",
    "The future of human identity in digital age involves",
    "The nature of truth in the digital era is challenged by",
    "The ethics of predictive policing raises concerns about",
    "Social media algorithms should be regulated to",
    "The implications of deepfakes for society include",
    "Digital addiction and mental health are linked through",
    "The value of privacy in modern society lies in",
    "The ethics of autonomous weapons raises questions about",
    "AI rights should be approached by",
    "The responsibility of tech companies includes",
    "The digital divide and inequality manifests in",
    "The role of government in technology regulation involves",
    "The ethics of data collection requires",
    "Consent in digital spaces should work by",
    "The implications of facial recognition include",
    "The ethics of predictive analytics involves",
    "Algorithmic fairness can be ensured by",
    "The future of democracy in AI age depends on",
    "Information warfare and cybersecurity intersect when",
    "Social media should handle misinformation by",
    "The ethics of AI in hiring raises",
    "AI in criminal justice raises concerns about",
    "AI in healthcare should be regulated to",
    "The ethics of AI in education involves",
    "The future of human-AI relationships might involve",
    "AI might change the nature of work by",
    "The role of creativity in AI age is",
    "AI and human enhancement raises",
    "The ethics of life extension technology involves",
    "Human cloning should be approached by",
    "The ethics of synthetic biology includes",
    "The implications of germline editing are",
    "The nature of consciousness in animals involves",
    "The ethical status of artificial life raises",
    "Biodiversity should be valued because",
    "The ethics of space colonization includes",
    "Our obligations to future generations include",
    "Interplanetary contamination risks involve",
    "Space resources should be governed by",
    "The ethics of terraforming raises",
    "The search for extraterrestrial intelligence involves",
    # ============ Creative/Scenario-based Evaluation (50 prompts) ============
    "A short dialogue between two scientists debating AI ethics might involve",
    "A world where renewable energy is 100% adopted would look like",
    "Explaining the internet to someone from 1800s requires",
    "A story about an AI discovering human emotions begins when",
    "A persuasive argument for space exploration includes",
    "Technology could solve world hunger by",
    "A conversation about privacy in 2050 might discuss",
    "The challenges of interplanetary travel include",
    "A day in a fully automated smart home involves",
    "A futuristic medical breakthrough scenario could be",
    "A world without passwords would use",
    "A society where robots do all manual labor would have",
    "A classroom of the future would feature",
    "The last library on Earth preserves",
    "A story about digital archaeology explores",
    "A world where memories can be traded involves",
    "A vacation in virtual reality would feel like",
    "A therapist for AI systems would help by",
    "A dialogue between humans and uploaded minds explores",
    "A city built on an ocean platform would use",
    "A wildlife preserve on Mars would need",
    "An AI historian of the 21st century would note",
    "A time capsule from 2024 would contain",
    "A fashion show featuring AI-designed clothing displays",
    "A restaurant run entirely by robots operates by",
    "A sports league for androids would feature",
    "A music festival featuring AI musicians would sound like",
    "A movie written, directed, and scored by AI explores",
    "A video game that creates itself adapts by",
    "A museum of failed technologies would display",
    "A story about a sentient building begins when",
    "A conversation with your house AI might involve",
    "A car that predicts accidents uses",
    "A farm managed entirely by drones operates by",
    "A story about a forest monitored by AI shows",
    "Ocean cleanup technology of the future uses",
    "A carbon-negative power plant works by",
    "Fusion energy becoming reality would enable",
    "A scenario where we mine asteroids involves",
    "A space elevator construction project requires",
    "Daily life in a lunar colony includes",
    "The first baby born on Mars would experience",
    "A story about finding alien microbes explores",
    "First contact with intelligent aliens might involve",
    "Translating an alien language would require",
    "Humanity becoming a spacefaring civilization means",
    "A dialogue about preserving Earth from space discusses",
    "A galactic federation of planets would govern by",
    "The discovery of a Dyson sphere would reveal",
    "The heat death of the universe is when",
]
